/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as RolloutApi from "../../..";
export declare namespace PublicObject {
    interface Options {
        environment?: core.Supplier<environments.RolloutApiEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
        privateAppLegacy: core.Supplier<string>;
        privateApp: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class PublicObject {
    protected readonly _options: PublicObject.Options;
    constructor(_options: PublicObject.Options);
    postCrmV3ObjectsContactsMergeMerge(request: RolloutApi.PublicMergeInput, requestOptions?: PublicObject.RequestOptions): Promise<RolloutApi.SimplePublicObject>;
    protected _getAuthorizationHeader(): Promise<string>;
}
