/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import { Batch } from "./api/resources/batch/client/Client";
import { Basic } from "./api/resources/basic/client/Client";
import { PublicObject } from "./api/resources/publicObject/client/Client";
import { Gdpr } from "./api/resources/gdpr/client/Client";
import { Search } from "./api/resources/search/client/Client";
export declare namespace RolloutApiClient {
    interface Options {
        environment?: core.Supplier<environments.RolloutApiEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
        privateAppLegacy: core.Supplier<string>;
        privateApp: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class RolloutApiClient {
    protected readonly _options: RolloutApiClient.Options;
    constructor(_options: RolloutApiClient.Options);
    protected _batch: Batch | undefined;
    get batch(): Batch;
    protected _basic: Basic | undefined;
    get basic(): Basic;
    protected _publicObject: PublicObject | undefined;
    get publicObject(): PublicObject;
    protected _gdpr: Gdpr | undefined;
    get gdpr(): Gdpr;
    protected _search: Search | undefined;
    get search(): Search;
}
