"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RolloutApiClient = void 0;
const Client_1 = require("./api/resources/batch/client/Client");
const Client_2 = require("./api/resources/basic/client/Client");
const Client_3 = require("./api/resources/publicObject/client/Client");
const Client_4 = require("./api/resources/gdpr/client/Client");
const Client_5 = require("./api/resources/search/client/Client");
class RolloutApiClient {
    constructor(_options) {
        this._options = _options;
    }
    get batch() {
        var _a;
        return ((_a = this._batch) !== null && _a !== void 0 ? _a : (this._batch = new Client_1.Batch(this._options)));
    }
    get basic() {
        var _a;
        return ((_a = this._basic) !== null && _a !== void 0 ? _a : (this._basic = new Client_2.Basic(this._options)));
    }
    get publicObject() {
        var _a;
        return ((_a = this._publicObject) !== null && _a !== void 0 ? _a : (this._publicObject = new Client_3.PublicObject(this._options)));
    }
    get gdpr() {
        var _a;
        return ((_a = this._gdpr) !== null && _a !== void 0 ? _a : (this._gdpr = new Client_4.Gdpr(this._options)));
    }
    get search() {
        var _a;
        return ((_a = this._search) !== null && _a !== void 0 ? _a : (this._search = new Client_5.Search(this._options)));
    }
}
exports.RolloutApiClient = RolloutApiClient;
