/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const RolloutApiEnvironment: {
    readonly Default: "https://api.hubapi.com";
};
export declare type RolloutApiEnvironment = typeof RolloutApiEnvironment.Default;
