"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RolloutApiEnvironment = void 0;
exports.RolloutApiEnvironment = {
    Default: "https://api.hubapi.com",
};
