/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const AssociationSpec: core.serialization.ObjectSchema<serializers.AssociationSpec.Raw, RolloutApi.AssociationSpec>;
export declare namespace AssociationSpec {
    interface Raw {
        associationCategory: serializers.AssociationSpecAssociationCategory.Raw;
        associationTypeId: number;
    }
}
