/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const AssociatedId: core.serialization.ObjectSchema<serializers.AssociatedId.Raw, RolloutApi.AssociatedId>;
export declare namespace AssociatedId {
    interface Raw {
        id: string;
        type: string;
    }
}
