/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const AssociationSpecAssociationCategory: core.serialization.Schema<serializers.AssociationSpecAssociationCategory.Raw, RolloutApi.AssociationSpecAssociationCategory>;
export declare namespace AssociationSpecAssociationCategory {
    type Raw = "HUBSPOT_DEFINED" | "USER_DEFINED" | "INTEGRATOR_DEFINED";
}
