/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const BatchResponseSimplePublicObject: core.serialization.ObjectSchema<serializers.BatchResponseSimplePublicObject.Raw, RolloutApi.BatchResponseSimplePublicObject>;
export declare namespace BatchResponseSimplePublicObject {
    interface Raw {
        completedAt: string;
        requestedAt?: string | null;
        startedAt: string;
        links?: Record<string, string> | null;
        results: serializers.SimplePublicObject.Raw[];
        status: serializers.BatchResponseSimplePublicObjectStatus.Raw;
    }
}
