/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const BatchResponseSimplePublicObjectWithErrors: core.serialization.ObjectSchema<serializers.BatchResponseSimplePublicObjectWithErrors.Raw, RolloutApi.BatchResponseSimplePublicObjectWithErrors>;
export declare namespace BatchResponseSimplePublicObjectWithErrors {
    interface Raw {
        completedAt: string;
        numErrors?: number | null;
        requestedAt?: string | null;
        startedAt: string;
        links?: Record<string, string> | null;
        results: serializers.SimplePublicObject.Raw[];
        errors?: serializers.StandardError.Raw[] | null;
        status: serializers.BatchResponseSimplePublicObjectWithErrorsStatus.Raw;
    }
}
