/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const BatchResponseSimplePublicObjectWithErrorsStatus: core.serialization.Schema<serializers.BatchResponseSimplePublicObjectWithErrorsStatus.Raw, RolloutApi.BatchResponseSimplePublicObjectWithErrorsStatus>;
export declare namespace BatchResponseSimplePublicObjectWithErrorsStatus {
    type Raw = "PENDING" | "PROCESSING" | "CANCELED" | "COMPLETE";
}
