/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const CollectionResponseSimplePublicObjectWithAssociationsForwardPaging: core.serialization.ObjectSchema<serializers.CollectionResponseSimplePublicObjectWithAssociationsForwardPaging.Raw, RolloutApi.CollectionResponseSimplePublicObjectWithAssociationsForwardPaging>;
export declare namespace CollectionResponseSimplePublicObjectWithAssociationsForwardPaging {
    interface Raw {
        paging?: serializers.ForwardPaging.Raw | null;
        results: serializers.SimplePublicObjectWithAssociations.Raw[];
    }
}
