/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const CollectionResponseAssociatedId: core.serialization.ObjectSchema<serializers.CollectionResponseAssociatedId.Raw, RolloutApi.CollectionResponseAssociatedId>;
export declare namespace CollectionResponseAssociatedId {
    interface Raw {
        paging?: serializers.Paging.Raw | null;
        results: serializers.AssociatedId.Raw[];
    }
}
