/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const CollectionResponseWithTotalSimplePublicObjectForwardPaging: core.serialization.ObjectSchema<serializers.CollectionResponseWithTotalSimplePublicObjectForwardPaging.Raw, RolloutApi.CollectionResponseWithTotalSimplePublicObjectForwardPaging>;
export declare namespace CollectionResponseWithTotalSimplePublicObjectForwardPaging {
    interface Raw {
        total: number;
        paging?: serializers.ForwardPaging.Raw | null;
        results: serializers.SimplePublicObject.Raw[];
    }
}
