/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const FilterGroup: core.serialization.ObjectSchema<serializers.FilterGroup.Raw, RolloutApi.FilterGroup>;
export declare namespace FilterGroup {
    interface Raw {
        filters: serializers.Filter.Raw[];
    }
}
