/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const ForwardPaging: core.serialization.ObjectSchema<serializers.ForwardPaging.Raw, RolloutApi.ForwardPaging>;
export declare namespace ForwardPaging {
    interface Raw {
        next?: serializers.NextPage.Raw | null;
    }
}
