/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const OauthScope: core.serialization.Schema<serializers.OauthScope.Raw, RolloutApi.OauthScope>;
export declare namespace OauthScope {
    type Raw = "crm.objects.quotes.write" | "crm.objects.deals.read" | "crm.objects.line_items.read" | "crm.objects.deals.write" | "crm.objects.quotes.read" | "crm.objects.line_items.write" | "crm.objects.companies.read" | "crm.objects.companies.write" | "crm.objects.contacts.write" | "crm.objects.contacts.read";
}
