/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const Paging: core.serialization.ObjectSchema<serializers.Paging.Raw, RolloutApi.Paging>;
export declare namespace Paging {
    interface Raw {
        next?: serializers.NextPage.Raw | null;
        prev?: serializers.PreviousPage.Raw | null;
    }
}
