/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const PreviousPage: core.serialization.ObjectSchema<serializers.PreviousPage.Raw, RolloutApi.PreviousPage>;
export declare namespace PreviousPage {
    interface Raw {
        before: string;
        link?: string | null;
    }
}
