/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const PublicAssociationsForObject: core.serialization.ObjectSchema<serializers.PublicAssociationsForObject.Raw, RolloutApi.PublicAssociationsForObject>;
export declare namespace PublicAssociationsForObject {
    interface Raw {
        types: serializers.AssociationSpec.Raw[];
        to: serializers.PublicObjectId.Raw;
    }
}
