/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const PublicObjectId: core.serialization.ObjectSchema<serializers.PublicObjectId.Raw, RolloutApi.PublicObjectId>;
export declare namespace PublicObjectId {
    interface Raw {
        id: string;
    }
}
