/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const SimplePublicObjectId: core.serialization.ObjectSchema<serializers.SimplePublicObjectId.Raw, RolloutApi.SimplePublicObjectId>;
export declare namespace SimplePublicObjectId {
    interface Raw {
        id: string;
    }
}
