/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const SimplePublicObjectInputForCreate: core.serialization.ObjectSchema<serializers.SimplePublicObjectInputForCreate.Raw, RolloutApi.SimplePublicObjectInputForCreate>;
export declare namespace SimplePublicObjectInputForCreate {
    interface Raw {
        associations: serializers.PublicAssociationsForObject.Raw[];
        properties: Record<string, string>;
    }
}
