/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const SimplePublicObjectWithAssociations: core.serialization.ObjectSchema<serializers.SimplePublicObjectWithAssociations.Raw, RolloutApi.SimplePublicObjectWithAssociations>;
export declare namespace SimplePublicObjectWithAssociations {
    interface Raw {
        associations?: Record<string, serializers.CollectionResponseAssociatedId.Raw> | null;
        createdAt: string;
        archived?: boolean | null;
        archivedAt?: string | null;
        propertiesWithHistory?: Record<string, serializers.ValueWithTimestamp.Raw[]> | null;
        id: string;
        properties: Record<string, string | null | undefined>;
        updatedAt: string;
    }
}
