/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const SimplePublicObjectBatchInput: core.serialization.ObjectSchema<serializers.SimplePublicObjectBatchInput.Raw, RolloutApi.SimplePublicObjectBatchInput>;
export declare namespace SimplePublicObjectBatchInput {
    interface Raw {
        idProperty?: string | null;
        id: string;
        properties: Record<string, string>;
    }
}
