/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const SimplePublicObject: core.serialization.ObjectSchema<serializers.SimplePublicObject.Raw, RolloutApi.SimplePublicObject>;
export declare namespace SimplePublicObject {
    interface Raw {
        createdAt: string;
        archived?: boolean | null;
        archivedAt?: string | null;
        propertiesWithHistory?: Record<string, serializers.ValueWithTimestamp.Raw[]> | null;
        id: string;
        properties: Record<string, string | null | undefined>;
        updatedAt: string;
    }
}
