/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const StandardError: core.serialization.ObjectSchema<serializers.StandardError.Raw, RolloutApi.StandardError>;
export declare namespace StandardError {
    interface Raw {
        subCategory?: serializers.StandardErrorSubCategory.Raw | null;
        context: Record<string, string[]>;
        links: Record<string, string>;
        id?: string | null;
        category: string;
        message: string;
        errors: serializers.ErrorDetail.Raw[];
        status: string;
    }
}
