/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const StandardErrorSubCategory: core.serialization.ObjectSchema<serializers.StandardErrorSubCategory.Raw, RolloutApi.StandardErrorSubCategory>;
export declare namespace StandardErrorSubCategory {
    interface Raw {
    }
}
