/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as RolloutApi from "../../api";
import * as core from "../../core";
export declare const ValueWithTimestamp: core.serialization.ObjectSchema<serializers.ValueWithTimestamp.Raw, RolloutApi.ValueWithTimestamp>;
export declare namespace ValueWithTimestamp {
    interface Raw {
        sourceId?: string | null;
        sourceType: string;
        sourceLabel?: string | null;
        updatedByUserId?: number | null;
        value: string;
        timestamp: string;
    }
}
