"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AssociationSpecAssociationCategory = void 0;
exports.AssociationSpecAssociationCategory = {
    HubspotDefined: "HUBSPOT_DEFINED",
    UserDefined: "USER_DEFINED",
    IntegratorDefined: "INTEGRATOR_DEFINED",
};
