/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type AssociationSpecAssociationCategory = "HUBSPOT_DEFINED" | "USER_DEFINED" | "INTEGRATOR_DEFINED";
export declare const AssociationSpecAssociationCategory: {
    readonly HubspotDefined: "HUBSPOT_DEFINED";
    readonly UserDefined: "USER_DEFINED";
    readonly IntegratorDefined: "INTEGRATOR_DEFINED";
};
