/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "..";
export interface AssociationSpec {
    associationCategory: RolloutApi.AssociationSpecAssociationCategory;
    associationTypeId: number;
}
