/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "..";
export interface BatchResponseSimplePublicObjectWithErrors {
    completedAt: Date;
    numErrors?: number;
    requestedAt?: Date;
    startedAt: Date;
    links?: Record<string, string>;
    results: RolloutApi.SimplePublicObject[];
    errors?: RolloutApi.StandardError[];
    status: RolloutApi.BatchResponseSimplePublicObjectWithErrorsStatus;
}
