/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "..";
export interface BatchResponseSimplePublicObject {
    completedAt: Date;
    requestedAt?: Date;
    startedAt: Date;
    links?: Record<string, string>;
    results: RolloutApi.SimplePublicObject[];
    status: RolloutApi.BatchResponseSimplePublicObjectStatus;
}
