/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type BatchResponseSimplePublicObjectStatus = "PENDING" | "PROCESSING" | "CANCELED" | "COMPLETE";
export declare const BatchResponseSimplePublicObjectStatus: {
    readonly Pending: "PENDING";
    readonly Processing: "PROCESSING";
    readonly Canceled: "CANCELED";
    readonly Complete: "COMPLETE";
};
