"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BatchResponseSimplePublicObjectWithErrorsStatus = void 0;
exports.BatchResponseSimplePublicObjectWithErrorsStatus = {
    Pending: "PENDING",
    Processing: "PROCESSING",
    Canceled: "CANCELED",
    Complete: "COMPLETE",
};
