/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "..";
export interface CollectionResponseAssociatedId {
    paging?: RolloutApi.Paging;
    results: RolloutApi.AssociatedId[];
}
