/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "..";
export interface CollectionResponseSimplePublicObjectWithAssociationsForwardPaging {
    paging?: RolloutApi.ForwardPaging;
    results: RolloutApi.SimplePublicObjectWithAssociations[];
}
