/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "..";
export interface CollectionResponseWithTotalSimplePublicObjectForwardPaging {
    total: number;
    paging?: RolloutApi.ForwardPaging;
    results: RolloutApi.SimplePublicObject[];
}
