"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FilterOperator = void 0;
exports.FilterOperator = {
    Eq: "EQ",
    Neq: "NEQ",
    Lt: "LT",
    Lte: "LTE",
    Gt: "GT",
    Gte: "GTE",
    Between: "BETWEEN",
    In: "IN",
    NotIn: "NOT_IN",
    HasProperty: "HAS_PROPERTY",
    NotHasProperty: "NOT_HAS_PROPERTY",
    ContainsToken: "CONTAINS_TOKEN",
    NotContainsToken: "NOT_CONTAINS_TOKEN",
};
