/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * null
 */
export declare type FilterOperator = "EQ" | "NEQ" | "LT" | "LTE" | "GT" | "GTE" | "BETWEEN" | "IN" | "NOT_IN" | "HAS_PROPERTY" | "NOT_HAS_PROPERTY" | "CONTAINS_TOKEN" | "NOT_CONTAINS_TOKEN";
export declare const FilterOperator: {
    readonly Eq: "EQ";
    readonly Neq: "NEQ";
    readonly Lt: "LT";
    readonly Lte: "LTE";
    readonly Gt: "GT";
    readonly Gte: "GTE";
    readonly Between: "BETWEEN";
    readonly In: "IN";
    readonly NotIn: "NOT_IN";
    readonly HasProperty: "HAS_PROPERTY";
    readonly NotHasProperty: "NOT_HAS_PROPERTY";
    readonly ContainsToken: "CONTAINS_TOKEN";
    readonly NotContainsToken: "NOT_CONTAINS_TOKEN";
};
