/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "..";
export interface Filter {
    highValue?: string;
    propertyName: string;
    values?: string[];
    value?: string;
    /** null */
    operator: RolloutApi.FilterOperator;
}
