"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OauthScope = void 0;
exports.OauthScope = {
    CrmObjectsQuotesWrite: "crm.objects.quotes.write",
    CrmObjectsDealsRead: "crm.objects.deals.read",
    CrmObjectsLineItemsRead: "crm.objects.line_items.read",
    CrmObjectsDealsWrite: "crm.objects.deals.write",
    CrmObjectsQuotesRead: "crm.objects.quotes.read",
    CrmObjectsLineItemsWrite: "crm.objects.line_items.write",
    CrmObjectsCompaniesRead: "crm.objects.companies.read",
    CrmObjectsCompaniesWrite: "crm.objects.companies.write",
    CrmObjectsContactsWrite: "crm.objects.contacts.write",
    CrmObjectsContactsRead: "crm.objects.contacts.read",
};
