/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type OauthScope = 
/**
 * Quotes */
"crm.objects.quotes.write"
/** */
 | "crm.objects.deals.read"
/**
 * Line Items */
 | "crm.objects.line_items.read"
/** */
 | "crm.objects.deals.write"
/**
 * Quotes */
 | "crm.objects.quotes.read"
/**
 * Line Items */
 | "crm.objects.line_items.write"
/** */
 | "crm.objects.companies.read"
/** */
 | "crm.objects.companies.write"
/** */
 | "crm.objects.contacts.write"
/** */
 | "crm.objects.contacts.read";
export declare const OauthScope: {
    readonly CrmObjectsQuotesWrite: "crm.objects.quotes.write";
    readonly CrmObjectsDealsRead: "crm.objects.deals.read";
    readonly CrmObjectsLineItemsRead: "crm.objects.line_items.read";
    readonly CrmObjectsDealsWrite: "crm.objects.deals.write";
    readonly CrmObjectsQuotesRead: "crm.objects.quotes.read";
    readonly CrmObjectsLineItemsWrite: "crm.objects.line_items.write";
    readonly CrmObjectsCompaniesRead: "crm.objects.companies.read";
    readonly CrmObjectsCompaniesWrite: "crm.objects.companies.write";
    readonly CrmObjectsContactsWrite: "crm.objects.contacts.write";
    readonly CrmObjectsContactsRead: "crm.objects.contacts.read";
};
