/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "..";
export interface PublicAssociationsForObject {
    types: RolloutApi.AssociationSpec[];
    to: RolloutApi.PublicObjectId;
}
