/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "..";
export interface SimplePublicObjectInputForCreate {
    associations: RolloutApi.PublicAssociationsForObject[];
    properties: Record<string, string>;
}
