/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SimplePublicObjectBatchInput {
    idProperty?: string;
    id: string;
    properties: Record<string, string>;
}
