/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "..";
export interface StandardError {
    subCategory?: RolloutApi.StandardErrorSubCategory;
    context: Record<string, string[]>;
    links: Record<string, string>;
    id?: string;
    category: string;
    message: string;
    errors: RolloutApi.ErrorDetail[];
    status: string;
}
