/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ValueWithTimestamp {
    sourceId?: string;
    sourceType: string;
    sourceLabel?: string;
    updatedByUserId?: number;
    value: string;
    timestamp: Date;
}
