/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as RolloutApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const PublicObjectSearchRequest: core.serialization.Schema<serializers.PublicObjectSearchRequest.Raw, RolloutApi.PublicObjectSearchRequest>;
export declare namespace PublicObjectSearchRequest {
    interface Raw {
        query?: string | null;
        limit: number;
        after: string;
        sorts: string[];
        properties: string[];
        filterGroups: serializers.FilterGroup.Raw[];
    }
}
