/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "../../../..";
/**
 * @example
 *     {
 *         inputs: [{
 *                 id: "1",
 *                 properties: {
 *                     "email": "bcooper@biglytics.net",
 *                     "phone": "(877) 929-0687",
 *                     "company": "Biglytics",
 *                     "website": "biglytics.net",
 *                     "lastname": "Cooper",
 *                     "firstname": "Bryan"
 *                 }
 *             }]
 *     }
 */
export interface BatchInputSimplePublicObjectBatchInput {
    inputs: RolloutApi.SimplePublicObjectBatchInput[];
}
