/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "../../../..";
/**
 * @example
 *     {
 *         inputs: [{
 *                 id: "id"
 *             }]
 *     }
 */
export interface BatchInputSimplePublicObjectId {
    inputs: RolloutApi.SimplePublicObjectId[];
}
