/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as RolloutApi from "../../../..";
/**
 * @example
 *     {
 *         limit: 1,
 *         after: "after",
 *         sorts: ["sorts"],
 *         properties: ["properties"],
 *         filterGroups: [{
 *                 filters: [{
 *                         propertyName: "propertyName",
 *                         operator: RolloutApi.FilterOperator.Eq
 *                     }]
 *             }]
 *     }
 */
export interface PublicObjectSearchRequest {
    query?: string;
    limit: number;
    after: string;
    sorts: string[];
    properties: string[];
    filterGroups: RolloutApi.FilterGroup[];
}
