/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         objectId: "objectId"
 *     }
 */
export interface PublicGdprDeleteInput {
    idProperty?: string;
    objectId: string;
}
