/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as RolloutApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const SimplePublicObjectInput: core.serialization.Schema<serializers.SimplePublicObjectInput.Raw, RolloutApi.SimplePublicObjectInput>;
export declare namespace SimplePublicObjectInput {
    interface Raw {
        properties: Record<string, string>;
    }
}
