/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         objectIdToMerge: "objectIdToMerge",
 *         primaryObjectId: "primaryObjectId"
 *     }
 */
export interface PublicMergeInput {
    objectIdToMerge: string;
    primaryObjectId: string;
}
