/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as RolloutApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const PublicGdprDeleteInput: core.serialization.Schema<serializers.PublicGdprDeleteInput.Raw, RolloutApi.PublicGdprDeleteInput>;
export declare namespace PublicGdprDeleteInput {
    interface Raw {
        idProperty?: string | null;
        objectId: string;
    }
}
