/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as RolloutApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const PublicMergeInput: core.serialization.Schema<serializers.PublicMergeInput.Raw, RolloutApi.PublicMergeInput>;
export declare namespace PublicMergeInput {
    interface Raw {
        objectIdToMerge: string;
        primaryObjectId: string;
    }
}
