/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface GetCrmV3ObjectsContactsContactIdGetByIdRequest {
    /**
     * A comma separated list of the properties to be returned in the response. If any of the specified properties are not present on the requested object(s), they will be ignored.
     */
    properties?: string | string[];
    /**
     * A comma separated list of the properties to be returned along with their history of previous values. If any of the specified properties are not present on the requested object(s), they will be ignored.
     */
    propertiesWithHistory?: string | string[];
    /**
     * A comma separated list of object types to retrieve associated IDs for. If any of the specified associations do not exist, they will be ignored.
     */
    associations?: string | string[];
    /**
     * Whether to return only results that have been archived.
     */
    archived?: boolean;
}
