/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         properties: {
 *             "email": "bcooper@biglytics.net",
 *             "phone": "(877) 929-0687",
 *             "company": "Biglytics",
 *             "website": "biglytics.net",
 *             "lastname": "Cooper",
 *             "firstname": "Bryan"
 *         }
 *     }
 */
export interface SimplePublicObjectInput {
    properties: Record<string, string>;
}
