/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as RolloutApi from "../../..";
export declare namespace Search {
    interface Options {
        environment?: core.Supplier<environments.RolloutApiEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
        privateAppLegacy: core.Supplier<string>;
        privateApp: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class Search {
    protected readonly _options: Search.Options;
    constructor(_options: Search.Options);
    postCrmV3ObjectsContactsSearchDoSearch(request: RolloutApi.PublicObjectSearchRequest, requestOptions?: Search.RequestOptions): Promise<RolloutApi.CollectionResponseWithTotalSimplePublicObjectForwardPaging>;
    protected _getAuthorizationHeader(): Promise<string>;
}
