"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Basic = void 0;
const environments = __importStar(require("../../../../environments"));
const core = __importStar(require("../../../../core"));
const url_join_1 = __importDefault(require("url-join"));
const serializers = __importStar(require("../../../../serialization"));
const errors = __importStar(require("../../../../errors"));
class Basic {
    constructor(_options) {
        this._options = _options;
    }
    /**
     * Read an Object identified by `{contactId}`. `{contactId}` refers to the internal object ID. Control what is returned via the `properties` query param.
     *
     * @example
     *     await rolloutApi.basic.getCrmV3ObjectsContactsContactIdGetById("contactId", {})
     */
    getCrmV3ObjectsContactsContactIdGetById(contactId, request = {}, requestOptions) {
        var _a;
        return __awaiter(this, void 0, void 0, function* () {
            const { properties, propertiesWithHistory, associations, archived } = request;
            const _queryParams = {};
            if (properties != null) {
                if (Array.isArray(properties)) {
                    _queryParams["properties"] = properties.map((item) => item);
                }
                else {
                    _queryParams["properties"] = properties;
                }
            }
            if (propertiesWithHistory != null) {
                if (Array.isArray(propertiesWithHistory)) {
                    _queryParams["propertiesWithHistory"] = propertiesWithHistory.map((item) => item);
                }
                else {
                    _queryParams["propertiesWithHistory"] = propertiesWithHistory;
                }
            }
            if (associations != null) {
                if (Array.isArray(associations)) {
                    _queryParams["associations"] = associations.map((item) => item);
                }
                else {
                    _queryParams["associations"] = associations;
                }
            }
            if (archived != null) {
                _queryParams["archived"] = archived.toString();
            }
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_a = (yield core.Supplier.get(this._options.environment))) !== null && _a !== void 0 ? _a : environments.RolloutApiEnvironment.Default, `crm/v3/objects/contacts/${contactId}`),
                method: "GET",
                headers: {
                    Authorization: yield this._getAuthorizationHeader(),
                    "private-app-legacy": yield core.Supplier.get(this._options.privateAppLegacy),
                    "private-app": yield core.Supplier.get(this._options.privateApp),
                    "X-Fern-Language": "JavaScript",
                },
                contentType: "application/json",
                queryParameters: _queryParams,
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
            });
            if (_response.ok) {
                return yield serializers.SimplePublicObjectWithAssociations.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                });
            }
            if (_response.error.reason === "status-code") {
                throw new errors.RolloutApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.body,
                });
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.RolloutApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                    });
                case "timeout":
                    throw new errors.RolloutApiTimeoutError();
                case "unknown":
                    throw new errors.RolloutApiError({
                        message: _response.error.errorMessage,
                    });
            }
        });
    }
    /**
     * Move an Object identified by `{contactId}` to the recycling bin.
     *
     * @example
     *     await rolloutApi.basic.deleteCrmV3ObjectsContactsContactIdArchive("contactId")
     */
    deleteCrmV3ObjectsContactsContactIdArchive(contactId, requestOptions) {
        var _a;
        return __awaiter(this, void 0, void 0, function* () {
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_a = (yield core.Supplier.get(this._options.environment))) !== null && _a !== void 0 ? _a : environments.RolloutApiEnvironment.Default, `crm/v3/objects/contacts/${contactId}`),
                method: "DELETE",
                headers: {
                    Authorization: yield this._getAuthorizationHeader(),
                    "private-app-legacy": yield core.Supplier.get(this._options.privateAppLegacy),
                    "private-app": yield core.Supplier.get(this._options.privateApp),
                    "X-Fern-Language": "JavaScript",
                },
                contentType: "application/json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
            });
            if (_response.ok) {
                return;
            }
            if (_response.error.reason === "status-code") {
                throw new errors.RolloutApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.body,
                });
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.RolloutApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                    });
                case "timeout":
                    throw new errors.RolloutApiTimeoutError();
                case "unknown":
                    throw new errors.RolloutApiError({
                        message: _response.error.errorMessage,
                    });
            }
        });
    }
    /**
     * Perform a partial update of an Object identified by `{contactId}`. `{contactId}` refers to the internal object ID. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.
     *
     * @example
     *     await rolloutApi.basic.patchCrmV3ObjectsContactsContactIdUpdate("contactId", {
     *         properties: {
     *             "email": "bcooper@biglytics.net",
     *             "phone": "(877) 929-0687",
     *             "company": "Biglytics",
     *             "website": "biglytics.net",
     *             "lastname": "Cooper",
     *             "firstname": "Bryan"
     *         }
     *     })
     */
    patchCrmV3ObjectsContactsContactIdUpdate(contactId, request, requestOptions) {
        var _a;
        return __awaiter(this, void 0, void 0, function* () {
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_a = (yield core.Supplier.get(this._options.environment))) !== null && _a !== void 0 ? _a : environments.RolloutApiEnvironment.Default, `crm/v3/objects/contacts/${contactId}`),
                method: "PATCH",
                headers: {
                    Authorization: yield this._getAuthorizationHeader(),
                    "private-app-legacy": yield core.Supplier.get(this._options.privateAppLegacy),
                    "private-app": yield core.Supplier.get(this._options.privateApp),
                    "X-Fern-Language": "JavaScript",
                },
                contentType: "application/json",
                body: yield serializers.SimplePublicObjectInput.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
            });
            if (_response.ok) {
                return yield serializers.SimplePublicObject.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                });
            }
            if (_response.error.reason === "status-code") {
                throw new errors.RolloutApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.body,
                });
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.RolloutApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                    });
                case "timeout":
                    throw new errors.RolloutApiTimeoutError();
                case "unknown":
                    throw new errors.RolloutApiError({
                        message: _response.error.errorMessage,
                    });
            }
        });
    }
    /**
     * Read a page of contacts. Control what is returned via the `properties` query param.
     *
     * @example
     *     await rolloutApi.basic.getCrmV3ObjectsContactsGetPage({})
     */
    getCrmV3ObjectsContactsGetPage(request = {}, requestOptions) {
        var _a;
        return __awaiter(this, void 0, void 0, function* () {
            const { limit, after, properties, propertiesWithHistory, associations, archived } = request;
            const _queryParams = {};
            if (limit != null) {
                _queryParams["limit"] = limit.toString();
            }
            if (after != null) {
                _queryParams["after"] = after;
            }
            if (properties != null) {
                if (Array.isArray(properties)) {
                    _queryParams["properties"] = properties.map((item) => item);
                }
                else {
                    _queryParams["properties"] = properties;
                }
            }
            if (propertiesWithHistory != null) {
                if (Array.isArray(propertiesWithHistory)) {
                    _queryParams["propertiesWithHistory"] = propertiesWithHistory.map((item) => item);
                }
                else {
                    _queryParams["propertiesWithHistory"] = propertiesWithHistory;
                }
            }
            if (associations != null) {
                if (Array.isArray(associations)) {
                    _queryParams["associations"] = associations.map((item) => item);
                }
                else {
                    _queryParams["associations"] = associations;
                }
            }
            if (archived != null) {
                _queryParams["archived"] = archived.toString();
            }
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_a = (yield core.Supplier.get(this._options.environment))) !== null && _a !== void 0 ? _a : environments.RolloutApiEnvironment.Default, "crm/v3/objects/contacts"),
                method: "GET",
                headers: {
                    Authorization: yield this._getAuthorizationHeader(),
                    "private-app-legacy": yield core.Supplier.get(this._options.privateAppLegacy),
                    "private-app": yield core.Supplier.get(this._options.privateApp),
                    "X-Fern-Language": "JavaScript",
                },
                contentType: "application/json",
                queryParameters: _queryParams,
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
            });
            if (_response.ok) {
                return yield serializers.CollectionResponseSimplePublicObjectWithAssociationsForwardPaging.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                });
            }
            if (_response.error.reason === "status-code") {
                throw new errors.RolloutApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.body,
                });
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.RolloutApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                    });
                case "timeout":
                    throw new errors.RolloutApiTimeoutError();
                case "unknown":
                    throw new errors.RolloutApiError({
                        message: _response.error.errorMessage,
                    });
            }
        });
    }
    /**
     * Create a contact with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard contacts is provided.
     *
     * @example
     *     await rolloutApi.basic.postCrmV3ObjectsContactsCreate({
     *         associations: [{
     *                 types: [{
     *                         associationCategory: RolloutApi.AssociationSpecAssociationCategory.HubspotDefined,
     *                         associationTypeId: 1
     *                     }],
     *                 to: {
     *                     id: "id"
     *                 }
     *             }],
     *         properties: {
     *             "email": "bcooper@biglytics.net",
     *             "phone": "(877) 929-0687",
     *             "company": "Biglytics",
     *             "website": "biglytics.net",
     *             "lastname": "Cooper",
     *             "firstname": "Bryan"
     *         }
     *     })
     */
    postCrmV3ObjectsContactsCreate(request, requestOptions) {
        var _a;
        return __awaiter(this, void 0, void 0, function* () {
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_a = (yield core.Supplier.get(this._options.environment))) !== null && _a !== void 0 ? _a : environments.RolloutApiEnvironment.Default, "crm/v3/objects/contacts"),
                method: "POST",
                headers: {
                    Authorization: yield this._getAuthorizationHeader(),
                    "private-app-legacy": yield core.Supplier.get(this._options.privateAppLegacy),
                    "private-app": yield core.Supplier.get(this._options.privateApp),
                    "X-Fern-Language": "JavaScript",
                },
                contentType: "application/json",
                body: yield serializers.SimplePublicObjectInputForCreate.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "strip",
                }),
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
            });
            if (_response.ok) {
                return yield serializers.SimplePublicObject.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                });
            }
            if (_response.error.reason === "status-code") {
                throw new errors.RolloutApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.body,
                });
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.RolloutApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                    });
                case "timeout":
                    throw new errors.RolloutApiTimeoutError();
                case "unknown":
                    throw new errors.RolloutApiError({
                        message: _response.error.errorMessage,
                    });
            }
        });
    }
    _getAuthorizationHeader() {
        return __awaiter(this, void 0, void 0, function* () {
            return `Bearer ${yield core.Supplier.get(this._options.token)}`;
        });
    }
}
exports.Basic = Basic;
