/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as RolloutApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const BatchInputSimplePublicObjectInputForCreate: core.serialization.Schema<serializers.BatchInputSimplePublicObjectInputForCreate.Raw, RolloutApi.BatchInputSimplePublicObjectInputForCreate>;
export declare namespace BatchInputSimplePublicObjectInputForCreate {
    interface Raw {
        inputs: serializers.SimplePublicObjectInputForCreate.Raw[];
    }
}
