/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as RolloutApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const BatchInputSimplePublicObjectBatchInput: core.serialization.Schema<serializers.BatchInputSimplePublicObjectBatchInput.Raw, RolloutApi.BatchInputSimplePublicObjectBatchInput>;
export declare namespace BatchInputSimplePublicObjectBatchInput {
    interface Raw {
        inputs: serializers.SimplePublicObjectBatchInput.Raw[];
    }
}
